stages:
  - install
  - test
  - deploy

install-deps:
  stage: install
  image: python:3.10
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install flask
  artifacts:
    paths:
      - venv
  rules:
    - changes: ["*", "!README.md"]
    - when: never

test-run:
  stage: test
  image: python:3.10
  script:
    - source venv/bin/activate
    - python -m py_compile app.py
  dependencies:
    - install-deps
  rules:
    - changes: ["*", "!README.md"]
    - when: never

deploy-placeholder:
  stage: deploy
  script:
    - echo "Ứng dụng đã sẵn sàng deploy!"
  rules:
    - changes: ["*", "!README.md"]
    - when: never
